apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metaverse
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: metaverse
    server: https://kubernetes.default.svc
  source:
    path: production/metaverse
    repoURL: https://github.com/rshdhere/staging-ops.git
    targetRevision: HEAD
    directory:
      recurse: false
      jsonnet:
        extVars: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
